name: metrics

on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
  push:

env:
  IMAGE_BRANCH: ci-generated-metrics

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout branch
        run: git checkout --orphan $IMAGE_BRANCH
      - name: Generate metrics image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          template: classic
          config_timezone: Asia/Shanghai
          plugins_errors_fatal: yes
          output_action: none
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_indepth: no
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_notable: yes
          plugin_notable_repositories: no
      - name: Force push image
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git reset --hard
          git clean -df
          sudo cp /metrics_renders/* ./
          git add --all
          git commit -m "Update metrics image"
          git push --force --set-upstream origin $IMAGE_BRANCH
